require 'rubygems'
require 'rsolr'

class SolrHandler

  def query terms, fq_terms

# Direct connection
    solr = RSolr.connect :url => 'http://192.168.220.234:8983/solr/trecsolr/', :read_timeout => 120, :open_timeout => 120
    #puts solr.inspect

    response = solr.get 'query', :params => {:q => terms, :fl=>['id', 'score'], :fq=>fq_terms, :rows=>1000}
    puts response["response"]["docs"].inspect
    response["response"]["docs"]
  end
end

#SolrHandler.new.query ["emesis", "tachycardia", "hypoxia",  "hypotension", "study", "role", "high", "temperature", "time", "receptor", "treatment", "system", "transgenic", "signaling", "reduced", "induced", "dormancy", "revealed", "remains", "observations", "type", "neurons", "involved", "unknown", "temperatures", "principal", "small", "plants", "root", "plays", "suggesting", "sensor", "negative", "residing", "period", "regulation", "trigeminal", "presented", "vestibule", "supposedly", "phase", "remained", "transgenic lines", "rosettes", "response pathway", "suggested", "occurred", "thermotransduction", "thermosensory", "thermosensor", "release", "perennial", "prolonged", "six", "percentage", "relation", "short", "peach", "stem", "variations", "stimulated", "prominent", "partially", "cold", "record", "varied", "periodic", "reflected", "slow", "played", "pollen", "spectral", "output-oldest", "originally", "supports", "requirement", "cyclic", "seasonal", "peaches", "solar", "triggers", "reagent", "vegetation", "summer", "rosette", "vertical", "ambient"].join(" ")
#SolrHandler.new.query ["penton", "knob", "penton base", "crystal formation", "protein crystals", "acm", "roche", "expectorant", "acute cough", "diagnostic uncertainty", "elafin", "slpi", "dox", "nasal lavage", "homotypic", "pneumocystis", "intranuclear", "immunosuppressed", "inclusions", "balf", "sans", "ova", "spores", "dlco", "sort", "pb", "tachypnea", "bal", "crystals", "rnase", "ovalbumin", "asexual", "sweetened", "saliva", "pneumonia", "coughing", "sorbitol", "serious bacterial", "phagocytic", "crystalline", "splenic", "sensitized", "bronchitis", "bronchoalveolar", "salivary", "smoking cessation", "fungus", "spectra", "inhalation", "airways", "lavage", "aids", "diffusing", "crystal", "fiber", "folk", "spleen", "pap", "infected", "vectors", "route", "drops", "cytotoxic", "tracheobronchial foreign", "bronchial", "alveolar", "chromatin", "neutrophils", "genus", "diva", "partly", "influx", "fmf", "virus", "breath", "microscopy", "tracheal", "cytoplasmic", "lungs", "tract", "neutrophil", "expiratory", "nucleus", "aspiration", "accumulation", "sexual", "airway", "kidney", "deletion", "sulfur", "situ", "drug", "lower", "hr", "cough", "mode", "serum", "life", "fluorescence", "rvfv", "cells", "ventilated", "dyspnea", "define", "lewy", "infections", "resistant", "antibodies", "receiving", "spectrum", "staining", "viral", "occurrence", "levels", "sequencing", "cell", "rift", "elevated", "domains", "interleukin", "hematological", "sputum", "role", "foreign bodies", "ebola", "understood", "human", "samples", "cycle", "associated", "pulmonary", "macrophages", "liver", "asthma", "sources", "analyzed", "aspects", "fruiting", "score", "proliferation", "enzyme", "respiratory", "humans", "nuclear", "attenuated", "data", "infection", "conclude", "open", "stages", "domain", "response", "prescribing", "tracheobronchial", "causes", "cause", "water", "cytokine", "propose", "concentrations", "lung", "including", "roles", "immune", "forced", "protein", "measure", "transplant", "stage", "pml", "clinical", "higher", "level", "appears", "genome", "normal", "determine", "treatment", "free", "tb", "expression", "brain", "patients", "increase", "oxygenation", "polycomb", "bronchoscopic", "increased", "fluid", "subjects", "rule", "individuals", "majority", "inhibit", "presented", "activity", "lead", "will", "model", "studies", "uncertainty", "control", "status", "patient", "knowledge", "effects", "vitro", "inflammation", "reported", "experiments", "low", "risk", "observed", "six"]
